### ISSUE TITLE
add ability to default to author instead of nick if nick is None

### ISSUE THREAD

**Issue by blandcr** [blandcr/tychebot#5]

**Comment by Trugath** [comment]
I fixed this by replacing author.nick with author.display_name
display_name defaults to nickname and falls back on username if the user has no nick

**Comment by Trugath** [comment]
I'll submit a PR if you merge in the existing one.

**Comment by blandcr** [comment]
A+ thanks sounds good. I see these are in the last PR anyway so ignore the comment I made questioning about that.

**Comment by blandcr** [comment]
resolved with commit 81fe21b045a03f605af255e86fd1fa3cbf3943ac

**Comment by blandcr** [comment]
Closed with commit 81fe21b045a03f605af255e86fd1fa3cbf3943ac
